#include <bits/stdc++.h>
using namespace std;


void solve(std::string c){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string c;
    std::cin >> c;
    solve(c);
    return 0;
}
